### PR TITLE
Add `from_fn` generator factory

### PR DESCRIPTION
**Pull request by epage**
`pushgen::from_fn` mirrors `std::iter::from_fn`.  The struct lives with
the others in `pushgen::structs::FromFn`.

### CODE REVIEW

**Comment by epage** [comment]
After reading [about this](https://github.com/joaquintides/transrangers/blob/master/rust.md#conclusions), I was curious to give it a try in a "real world" application ([`typos`](https://github.com/crate-ci/typos)), so I'm adding support for what I need to start running benchmarks.

**Comment by AndWass** [comment]
Looks very nice! Thank you!

**Comment by epage** [comment]
Finally wrapped up my `pushgen` experiment: https://epage.github.io/blog/2021/07/pushgen-experiment/ ([reddit](https://www.reddit.com/r/rust/comments/ofpnwm/experiments_with_pushgen/)).

**Comment by AndWass** [comment]
Nice! Thank you for trying it out!

Just for my own understanding, you saw some decent improvements when comparing iterator code vs pushgen specifically but in the use-case of typos it isn't where the real bottleneck is (IO etc is much slower)?

**Pull request merged**
